# Generated by Django 2.2 on 2023-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='name',
            field=models.CharField(blank=True, db_column='NAME', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='administrator',
            name='tel',
            field=models.CharField(blank=True, db_column='TEL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='arrivalplace',
            field=models.CharField(blank=True, db_column='ARRIVALPLACE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='arrivaltime',
            field=models.CharField(blank=True, db_column='ARRIVALTIME', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='daparturedate',
            field=models.CharField(blank=True, db_column='DAPARTUREDATE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='dapartureplace',
            field=models.CharField(blank=True, db_column='DAPARTUREPLACE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='daparturetime',
            field=models.CharField(blank=True, db_column='DAPARTURETIME', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='passengeridnum',
            field=models.CharField(blank=True, db_column='PASSENGERIDNUM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='passengername',
            field=models.CharField(blank=True, db_column='PASSENGERNAME', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='price',
            field=models.IntegerField(blank=True, db_column='PRICE', null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='seattype',
            field=models.CharField(blank=True, db_column='SEATTYPE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deleted',
            name='trainid',
            field=models.CharField(blank=True, db_column='TRAINID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='daparturedate',
            field=models.CharField(blank=True, db_column='DAPARTUREDATE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketlist',
            name='daparturedate',
            field=models.CharField(blank=True, db_column='DAPARTUREDATE', max_length=100, null=True),
        ),
    ]
